export const ACTIV_NEW_ITEM_DIALOGE = "ACTIV_NEW_ITEM_DIALOGE";
export const RESET_NEW_ITEM_DIALOGE = "RESET_NEW_ITEM_DIALOGE";

export const RESET_CL_ERROR_MESSAGES = "RESET_CL_ERROR_MESSAGES";
export const RESET_CL_FORM = "RESET_CL_FORM";

export const CHANGE_ITEM_VALUES = "@@redux-form/CHANGE";
export const ADD_NEW_ITEM = "ADD_NEW_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
