export const ACTIV_NEW_ITEM_DIALOGE = "ACTIV_NEW_ITEM_DIALOGE";
export const RESET_NEW_ITEM_DIALOGE = "RESET_NEW_ITEM_DIALOGE";

export const RESET_CL_ERROR_MESSAGES = "RESET_CL_ERROR_MESSAGES";
export const RESET_CL_FORM = "RESET_CL_FORM";
